name: catchsunshine
favicon: null
layout_spectrum: 0.8569060687441379
typography_spectrum: 0.036680682795122266
title: We catch the moment called sunshine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.33942370652221143
  lightness: 0.6896516624838114
  saturation: 0.5097344710957259
  rhythmicContrast: 0.438603441696614
purpose: []
