name: catchsunshine
favicon: null
layout_spectrum: 0.93788
typography_spectrum: 0.56174
title: We catch the moment called sunshine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdccd4'
    - '#919eae'
    - '#152015'
    - '#394731'
    - '#465873'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
